version: "3"

services:
  weblate:
    image: weblate/weblate
    environment:
      - DEBUG=0
      - WEBLATE_SITE_DOMAIN=localhost
      - WEBLATE_EMAIL_HOST=sandbox.smtp.mailtrap.io
      - WEBLATE_EMAIL_HOST_USER=cbd29d787339bd
      - WEBLATE_EMAIL_HOST_PASSWORD=8958f7df502d0b
      - WEBLATE_ALLOWED_HOSTS=weblate.example.com,localhost
      - WEBLATE_ADMIN_PASSWORD=12345
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=weblate
      - POSTGRES_USER=weblate
      - POSTGRES_PASSWORD=weblate
    ports:
      - "6500:8080"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DATABASE=weblate
      - POSTGRES_USER=weblate
      - POSTGRES_PASSWORD=weblate

  cache:
    image: redis:6

  worker:
    image: weblate/weblate
    command: celery -A weblate.trans worker --loglevel=info
    environment:
      - DEBUG=0
      - WEBLATE_SITE_DOMAIN=localhost
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=weblate
      - POSTGRES_USER=weblate
      - POSTGRES_PASSWORD=weblate
